version: '3.1'
services:
  db:
    image: mysql
    container_name: sorteador
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - sorteador_data:/var/lib/mysql

volumes:
  sorteador_data: